name: couple_jet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  countries_utils: ^1.0.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.5.8
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^4.3.4+2
  flutter_switch: ^0.3.2
  form_field_validator: ^1.1.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.3.0
  google_sign_in: ^5.3.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.3.0
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.3
  regexed_validator: ^2.0.0+1
  swipe_cards: ^1.0.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - assets/
